// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDuLich.Data;

#nullable disable

namespace WebDuLich.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250322063000_WebDuLich")]
    partial class WebDuLich
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebDuLich.Models.Dondattour", b =>
                {
                    b.Property<int>("Madon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madon"));

                    b.Property<int>("Matour")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngaydat")
                        .HasColumnType("datetime2");

                    b.Property<int>("Songuoi")
                        .HasColumnType("int");

                    b.Property<decimal>("Tongtien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Madon");

                    b.HasIndex("Matour");

                    b.ToTable("Dondattour", (string)null);
                });

            modelBuilder.Entity("WebDuLich.Models.Tour", b =>
                {
                    b.Property<int>("Matour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matour"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiTour")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sokhach")
                        .HasColumnType("int");

                    b.Property<string>("Tentour")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Matour");

                    b.ToTable("Tour", (string)null);
                });

            modelBuilder.Entity("WebDuLich.Models.Dondattour", b =>
                {
                    b.HasOne("WebDuLich.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("Matour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });
#pragma warning restore 612, 618
        }
    }
}
