// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebDuLich.Data;

#nullable disable

namespace WebDuLich.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731174828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebDuLich.Models.Dondattour", b =>
                {
                    b.Property<int>("Madon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Madon"));

                    b.Property<string>("Emaildangki")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Matour")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Ngaydat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Songuoi")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tongtien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Madon");

                    b.HasIndex("Emaildangki");

                    b.HasIndex("Matour");

                    b.ToTable("Dondattour", (string)null);
                });

            modelBuilder.Entity("WebDuLich.Models.TaiKhoan", b =>
                {
                    b.Property<string>("Emaildangki")
                        .HasColumnType("text");

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Gioitinh")
                        .HasColumnType("text");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phanquyen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Sodienthoai")
                        .HasColumnType("text");

                    b.Property<string>("Tendangnhap")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Emaildangki");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("WebDuLich.Models.Tour", b =>
                {
                    b.Property<int>("Matour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Matour"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LoaiTour")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Mota")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKhoiHanh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sokhach")
                        .HasColumnType("integer");

                    b.Property<string>("Tentour")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Matour");

                    b.ToTable("Tour", (string)null);
                });

            modelBuilder.Entity("WebDuLich.Models.Dondattour", b =>
                {
                    b.HasOne("WebDuLich.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("Dondattours")
                        .HasForeignKey("Emaildangki")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDuLich.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("Matour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("WebDuLich.Models.TaiKhoan", b =>
                {
                    b.Navigation("Dondattours");
                });
#pragma warning restore 612, 618
        }
    }
}
